CREATE TABLE [LESSON].[LESSON] (
    [id] INT NOT NULL PRIMARY KEY,
    [Name] NVARCHAR(50) NOT NULL,
    [Description] NVARCHAR(250) NULL,
    [Risk] DECIMAL(12,2) NULL,
    [WorkType] NVARCHAR(600) NULL,
    [ExecutionMode] NVARCHAR(600) NULL,
    [updatedOn] DATETIME2 NULL,
  CONSTRAINT [FK_LESSON_PROJECT] FOREIGN KEY ([ProjectId]) REFERENCES [LESSON].[PROJECT]([id]
,
[Country] NVARCHAR(50) NULL,
[Commodity] NVARCHAR(50) NULL,