--CREATE TABLE [LESSON].[WORKTYPE] (
--    [id] INT NOT NULL PRIMARY KEY,
--    [Description] NVARCHAR(250) NULL,
--    [Name] NVARCHAR(50) NULL,
--    [IsActive] BIT NOT NULL,
--    [createdOn] DATETIME NULL,
--    [CreatedBy] NVARCHAR(50) NULL,
--    [updatedOn] DATETIME NULL,
--    [UpdatedBy] NVARCHAR(50) NULL
--);