name: dare-sql-cicd

on:
  push:
    branches:
      - main
    paths:
      - 'code/dare-sql-db.sln'
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - feature/*

permissions:
  id-token: write
  contents: read
  pull-requests: write
  checks: write
  issues: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build app for release
        run: msbuild ${{ github.workspace}}/code/dare-sql-db.sln -t:rebuild -verbosity:diag -property:Configuration=Release
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: DareDacpac
          path: ${{ github.workspace}}code/dare-sql-db/bin/Release
    
  deploy_de:
    uses: ./.github/workflows/dare-sql-deploy-template.yml
    needs: build
    with:
      environment: de
      dacpac: DareDacpac
      dacpacName: dare-sql-db.dacpac
      server: dare-sql.database.windows.net # ${{ secrets.SQL_SERVER }}
      database: ${{ secrets.SQL_DATABASE }}
      username: ${{ secrets.SQL_USERNAME }}
      password: ${{ secrets.SQL_PASSWORD }}

  # deploy_de1:
  #   uses: ./.github/workflow/dare-sql-deploy-template.yml
  #   needs: build
  #   with:
  #     environment: dev
  #     dacpac: DareDacpac
  #     dacpacName: dare-sql-db.dacpac
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  
