name: sql-deploy-template

on:
  workflow_call:
    inputs:
        environment:
            description: 'Environment to deploy to'
            required: true
            type: string
        artifactName:
            description: 'Name of the artifact to deploy'
            required: true
            type: string
        dacpacName:
            description: 'Name of the dacpac to deploy'
            required: true
            type: string
    secrets:
        AZURE_CLIENT_ID:
            required: true
        AZURE_TENANT_ID:
            required: true
        AZURE_SUBSCRIPTION_ID:
            required: true
        AZURE_CONNECTION_STRING:
            required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: windows-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Download Dacpac
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ github.workspace }}/code
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy dacpac
        uses: azure/sql-action@v2.2.1
        with:
          #server-name: ${{ secrets.AZURE_SERVER_NAME }}
          connection-string: ${{ secrets.AZURE_CONNECTION_STRING }}
          path-to-dacpac: ${{ github.workspace }}/code
          action: Publish
